# 监控并及时升级脚本中的“actions”版本，提高编译OpenWrt的成功率
# 监控脚本中的官方“actions”：uses: actions/checkout@v...，用来把脚本中的代码拉取到 Github 服务器上进行编译，官方地址：https://github.com/actions/checkout
# 监控脚本中的官方“actions”：actions/upload-artifact@v...，用来把编译好的固件上传到 Github 服务器上，官方地址：https://github.com/actions/upload-artifact
# 不修改，不升级，跳过脚本中的第三方磁盘空间扩容"actions"：uses: easimon/maximize-build-space@master，使用“@master”，会自动使用最新版本，不需要升级。地址：https://github.com/easimon/maximize-build-space

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"                    # 监控整个仓库的所有 workflow
    schedule:
      interval: "weekly"           # 每周检查一次，或改成"monthly"每月检查一次
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10       # 最多同时打开10个PR

    # 防止 dependabot.yml 自动修改第三方磁盘空间扩容 actions："easimon/maximize-build-space"，导致编译失败
    ignore:
      - dependency-name: "easimon/maximize-build-space"
